### ISSUE TITLE
lstm.py sLSTM class init_hidden batch_size question

### ISSUE THREAD

**Issue by willxxy** [myscience/x-lstm#4]
Hello, thanks for the great work. 

In the sLSTM module in `lstm.py` file, the current init_hidden function is currently like so 

```
def init_hidden(self) -> Tuple[Tensor, Tensor, Tensor, Tensor]:
        '''Initialize the hidden state of the sLSTM model.

        Args:
            batch_size (int): The batch size of the input sequence.

        Returns:
            Tuple[Tensor, Tensor, Tensor, Tensor]: The hidden state tuple containing the cell state,
                normalizer state, hidden state, and stabilizer state.
        '''
        
        n_0 = torch.ones (self.head_num * self.head_dim, device=self.device)
        c_0 = torch.zeros(self.head_num * self.head_dim, device=self.device)
        h_0 = torch.zeros(self.head_num * self.head_dim, device=self.device)
        m_0 = torch.zeros(self.head_num * self.head_dim, device=self.device)
        
        return c_0, n_0, h_0, m_0
```

Although the arguments say batch_size, it is not being passed in. I was wondering if this was intended. 

If not, would this be the correct way to do this ?

```
def init_hidden(self, bs : int) -> Tuple[Tensor, Tensor, Tensor, Tensor]:
        '''Initialize the hidden state of the sLSTM model.

        Args:
            batch_size (int): The batch size of the input sequence.

        Returns:
            Tuple[Tensor, Tensor, Tensor, Tensor]: The hidden state tuple containing the cell state,
                normalizer state, hidden state, and stabilizer state.
        '''
        
        n_0 = torch.ones (bs, self.head_num * self.head_dim, device=self.device)
        c_0 = torch.zeros(bs, self.head_num * self.head_dim, device=self.device)
        h_0 = torch.zeros(bs, self.head_num * self.head_dim, device=self.device)
        m_0 = torch.zeros(bs, self.head_num * self.head_dim, device=self.device)
        
        return c_0, n_0, h_0, m_0
```

Thank you.

**Comment by willxxy** [comment]
Upon further investigation I saw that this [pull request](https://github.com/myscience/x-lstm/pull/2) observed this as well, but it seems like this is supposed to be the intended usage of the hidden state initialization. Would you be able to clarify this if this was intended? Thank you!

**Comment by myscience** [comment]
Hi @willxxy, thank you so much for pointing this out. I quickly went through the code and indeed it seems that your version is the correct one! I assume I just forgot it in the initial version and later got (incorrectly) away with implicit broadcasting, which is not intended behavior (indeed you want different internal states for each batch, which correspond to different sequences). 

I have quickly updated a patch to the code, however I can only test it partially on the machine I am on at this moment. If you try it out feel free to let me know if there's anything off. Again, thank you so much for spotting this!

**Comment by willxxy** [comment]
Cool! thank you ~
